replicaCount: 1

image:
  repository: ghcr.io/sc-samir/clusterapp
  tag: sha-a20627e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: demo.p845.lecpac-consulting.dev
  path: /

appConfig:
  VECTOR_DIM: "384"
  RSS_FEEDS: "https://hnrss.org/frontpage,https://www.reddit.com/r/programming/.rss,https://techcrunch.com/feed/,https://www.theverge.com/rss/index.xml,https://feeds.arstechnica.com/arstechnica/index,https://www.infoq.com/feed/"
  INGEST_INTERVAL_MINUTES: "30"
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"

secrets:
  DATABASE_URL: "postgresql+psycopg://<user>:<password>@<host>:5432/<db>"

cronjob:
  enabled: true
  schedule: "*/30 * * * *"
