replicaCount: 1

image:
  repository: ghcr.io/sc-samir/clusterapp
  tag: sha-2c17ab9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: demo.p845.lecpac-consulting.dev
  path: /
  clusterIssuer: letsencrypt-prod

appConfig:
  VECTOR_DIM: "384"
  RSS_FEEDS: "https://hnrss.org/frontpage,https://www.reddit.com/r/programming/.rss,https://techcrunch.com/feed/,https://www.theverge.com/rss/index.xml,https://feeds.arstechnica.com/arstechnica/index,https://www.infoq.com/feed/"
  INGEST_INTERVAL_MINUTES: "30"
  EMBEDDING_MODEL: "/app/app/models/all-MiniLM-L6-v2"

secrets:
  existingSecret: "lecpac-rss-secret"

cronjob:
  enabled: true
  schedule: "*/30 * * * *"

resources:
  requests:
    cpu: "100m"
    memory: "900Mi"
  limits:
    cpu: "1"
    memory: "1.5Gi"

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2
